// Actividades adicionales de Gran Canaria verificadas en las páginas públicas
// facilitadas por OWA. Todas se confirman inicialmente por WhatsApp hasta que
// exista disponibilidad en tiempo real y contrato operativo con el proveedor.

const images = {
  buggy: 'https://buggypirates.com/wp-content/uploads/2025/10/websolobuggy-2073h.webp',
  dolphin: 'https://images.unsplash.com/photo-1518399681705-1c1a55e5e883?auto=format&fit=crop&w=1200&q=80',
  dive: 'https://zeusdivecenter.com/wp-content/uploads/2026/02/grancanaria-snorkel-trydive-scubadive-duiken-schnuppertauchen-dive-tauchen-maspalomas182.jpg',
  diveWide: 'https://zeusdivecenter.com/wp-content/uploads/2026/02/grancanaria-snorkel-trydive-scubadive-duiken-schnuppertauchen-dive-tauchen-maspalomas188.png',
  yacht: 'https://images.unsplash.com/photo-1571328532572-cb7899a8be7e?auto=format&fit=crop&w=1200&q=80',
  yachtWide: 'https://images.unsplash.com/photo-1526621480041-c4e2027dfe69?auto=format&fit=crop&w=1200&q=80',
  sunset: 'https://images.unsplash.com/photo-1499403474843-04e72c14df8a?auto=format&fit=crop&w=1200&q=80',
  catamaran: 'https://images.unsplash.com/photo-1564555449603-b0eefe1b9094?auto=format&fit=crop&w=1200&q=80',
  jetSki: 'https://images.unsplash.com/photo-1564633351631-e85bd59a91af?auto=format&fit=crop&w=1200&q=80',
  parasailing: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80',
  paddle: 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1200&q=80',
  boatParty: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
};

const infinityProvider = {
  id: 'infinity-boat-gc',
  name: 'Infinity Boat Tours',
};

const buggyProvider = {
  id: 'buggy-pirates',
  name: 'Buggypirates',
};

const dolphinProvider = {
  id: 'multiacuatic',
  name: 'Multiacuatic Dolphin & Whale',
};

const zeusProvider = {
  id: 'zeus-dive-center',
  name: 'Zeus Dive Center',
};

const nirvanaProvider = {
  id: 'nirvana-dreams',
  name: 'Nirvana Dreams',
};

const molinaProvider = {
  id: 'watersports-luis-molina',
  name: 'Watersports Luis Molina',
};

const infinityCancellation = {
  verifiedOn: '2026-08-11',
  noticeHours: 48,
  short: 'Cancelación gratuita hasta 48 horas antes.',
  details: 'Cancela con al menos 48 horas de antelación para recibir un reembolso completo.',
  sourceUrl: 'https://www.infinityboatgc.com/',
};

const zeusCancellation = {
  verifiedOn: '2026-08-11',
  noticeHours: 24,
  short: 'No se admiten cancelaciones con menos de 24 horas.',
  details: 'El proveedor indica que el cliente no puede cancelar con menos de 24 horas de antelación. La actividad puede cancelarse por motivos organizativos o de seguridad.',
  sourceUrl: 'https://zeusdivecenter.com/es/precios/',
};

const dolphinCancellation = {
  verifiedOn: '2026-08-11',
  noticeHours: null,
  short: 'Reembolso íntegro si el operador cancela por el estado del mar.',
  details: 'Si las condiciones del mar no permiten navegar, el operador cancela la salida y devuelve el 100% de lo pagado. Las cancelaciones solicitadas por el cliente deben confirmarse antes de reservar.',
  sourceUrl: 'https://dolphinwhales.es/product/dolphin-safari',
};

const getYourGuideCancellation = {
  verifiedOn: '2026-08-11',
  noticeHours: 24,
  short: 'Cancelación gratuita hasta 24 horas antes.',
  details: 'La actividad enlazada publica cancelación gratuita hasta 24 horas antes del comienzo.',
  sourceUrl: 'https://www.getyourguide.com/gran-canaria-l418/desde-puerto-rico-fiesta-en-barco-por-la-costa-t754827/',
};

function unpublishedCancellation(providerName, sourceUrl) {
  return {
    verifiedOn: '2026-08-11',
    noticeHours: null,
    short: 'Condiciones de cancelación a confirmar antes de reservar.',
    details: `${providerName} no muestra una política de cancelación completa y verificable en la página pública consultada. OWA confirmará las condiciones aplicables por WhatsApp antes de cobrar.`,
    sourceUrl,
  };
}

function normalizeTickets(ticketTypes, price, priceUnit) {
  const source = ticketTypes?.length
    ? ticketTypes
    : [{ id: 'standard', label: priceUnit === 'persona' ? 'Personas' : 'Reserva', price }];

  return source.map((ticket, index) => ({
    min: 0,
    max: 12,
    default: index === 0 ? 1 : 0,
    ...ticket,
  }));
}

function manualActivity({
  id,
  title,
  provider,
  sourceUrl,
  priceSourceUrl = sourceUrl,
  location,
  category = 'nauticas',
  price,
  priceUnit = 'persona',
  duration,
  image,
  description,
  shortDescription = description,
  included = ['Gestión de disponibilidad con el operador local', 'Información previa a la actividad'],
  notIncluded = ['Servicios opcionales no indicados expresamente'],
  meetingPoint,
  pickup = 'Consultar disponibilidad de recogida con OWA.',
  groupSize = 'Grupo a confirmar',
  insurance = 'Según condiciones del proveedor',
  languages = 'ES / EN',
  restrictions = ['La actividad está sujeta a disponibilidad y condiciones meteorológicas.'],
  cancellationPolicy,
  ticketTypes,
  timeSlots = ['Horario a confirmar'],
  featured = false,
}) {
  return {
    id,
    title,
    location,
    destination: 'gran-canaria',
    category,
    price,
    originalPrice: null,
    duration,
    rating: null,
    reviews: 0,
    featured,
    image,
    gallery: [image],
    shortDescription,
    description,
    included,
    notIncluded,
    meetingPoint,
    pickup,
    groupSize,
    insurance,
    languages,
    restrictions,
    provider: {
      ...provider,
      activityUrl: sourceUrl,
    },
    cancellationPolicy,
    ticketTypes: normalizeTickets(ticketTypes, price, priceUnit),
    timeSlots,
    priceUnit,
    paymentCurrency: 'EUR',
    bookingEnabled: false,
    priceVerifiedOn: '2026-08-11',
    priceSourceUrl,
  };
}

const infinityActivities = [
  manualActivity({
    id: 'infinity-yacht-sport-private',
    title: 'Yate Sport Privado — 4 horas',
    provider: infinityProvider,
    sourceUrl: 'https://www.infinityboatgc.com/excursion-en-yate-sport-privado',
    price: 600,
    priceUnit: 'grupo privado',
    duration: '4 horas',
    image: images.yacht,
    location: 'Puerto Rico, Gran Canaria',
    meetingPoint: 'Puerto Escala, Puerto Rico',
    pickup: 'Recogida y regreso desde alojamientos del sur con reserva previa.',
    groupSize: 'Hasta 10 pers.',
    insurance: 'Incluido',
    cancellationPolicy: infinityCancellation,
    description: 'Salida privada en yate para un grupo de hasta 10 personas, con aperitivos, barra libre, snorkel, paddle surf y plataforma flotante.',
    included: ['Yate privado con capitán', 'Aperitivos y bebidas', 'Snorkel y paddle surf', 'Seguro, impuestos y tasas', 'Traslado en el sur con reserva previa'],
    notIncluded: ['Toallas', 'Actividades acuáticas opcionales', 'Hora extra: 150 €'],
    ticketTypes: [
      { id: 'base_group', label: 'Grupo hasta 8 personas', price: 600, max: 1, default: 1 },
      { id: 'extra_guest', label: 'Pasajero extra (máx. 2)', price: 45, max: 2, default: 0 },
    ],
    timeSlots: ['10:30', '14:30', 'Sunset (verano)'],
    featured: true,
  }),
  manualActivity({
    id: 'infinity-yacht-private',
    title: 'Yate Infinity Privado — 4 horas',
    provider: infinityProvider,
    sourceUrl: 'https://www.infinityboatgc.com/excursion-privada-en-yate-infinity',
    price: 680,
    priceUnit: 'grupo privado',
    duration: '4 horas',
    image: images.yachtWide,
    location: 'Puerto Rico, Gran Canaria',
    meetingPoint: 'Puerto Escala, Puerto Rico',
    pickup: 'Recogida y regreso desde alojamientos del sur con reserva previa.',
    groupSize: 'Hasta 12 pers.',
    insurance: 'Incluido',
    cancellationPolicy: infinityCancellation,
    description: 'Experiencia exclusiva en yate privado por la costa de Mogán con aperitivos, barra libre, snorkel, paddle surf y plataforma flotante.',
    included: ['Yate privado con capitán y guía', 'Aperitivos y barra libre', 'Snorkel y 2 tablas de paddle surf', 'Seguro, impuestos y tasas', 'Traslado en el sur con reserva previa'],
    notIncluded: ['Toallas', 'Actividades acuáticas opcionales', 'Hora extra: 170 €'],
    ticketTypes: [
      { id: 'base_group', label: 'Grupo hasta 8 personas', price: 680, max: 1, default: 1 },
      { id: 'extra_guest', label: 'Pasajero extra (máx. 4)', price: 45, max: 4, default: 0 },
    ],
    timeSlots: ['09:30', '13:30', 'Sunset (verano)'],
    featured: true,
  }),
];

const buggyActivities = [
  manualActivity({
    id: 'buggy-pirates-tour',
    title: 'Buggy Pirates Tour',
    provider: buggyProvider,
    sourceUrl: 'https://buggypirates.com/buggies/',
    priceSourceUrl: 'https://widgets.bokun.io/online-sales/f48e670d-408e-464d-b220-83ecb660ac59/experience-calendar/608266?lang=es',
    price: 120,
    priceUnit: 'buggy',
    duration: '2 h 15 min',
    image: images.buggy,
    category: 'aventura',
    location: 'El Tablero, Gran Canaria',
    meetingPoint: 'Base Buggypirates, El Tablero',
    pickup: 'Traslados incluidos desde zonas turísticas seleccionadas.',
    groupSize: 'Consultar ocupación por buggy',
    cancellationPolicy: unpublishedCancellation('Buggypirates', 'https://buggypirates.com/buggies/'),
    description: 'Ruta guiada en buggy por el sur de Gran Canaria con salida desde El Tablero y traslados desde zonas turísticas seleccionadas.',
    included: ['Buggy y guía de ruta', 'Traslados desde zonas seleccionadas', 'Información de seguridad'],
    notIncluded: ['Servicios no indicados en la reserva del operador'],
    ticketTypes: [{ id: 'buggy', label: 'Buggy', price: 120, max: 6, default: 1 }],
    featured: true,
  }),
  manualActivity({
    id: 'buggy-pirates-family',
    title: 'Family & Friends Buggy Tour',
    provider: buggyProvider,
    sourceUrl: 'https://buggypirates.com/buggies/',
    priceSourceUrl: 'https://widgets.bokun.io/online-sales/f48e670d-408e-464d-b220-83ecb660ac59/experience-calendar/1104378?lang=es',
    price: 270,
    priceUnit: 'grupo',
    duration: '2 h 15 min',
    image: images.buggy,
    category: 'aventura',
    location: 'El Tablero, Gran Canaria',
    meetingPoint: 'Base Buggypirates, El Tablero',
    pickup: 'Traslados incluidos desde zonas turísticas seleccionadas.',
    groupSize: 'Configuración familiar para 3 participantes',
    cancellationPolicy: unpublishedCancellation('Buggypirates', 'https://buggypirates.com/buggies/'),
    description: 'Formato familiar y para grupos de amigos del tour en buggy de Buggypirates por el sur de Gran Canaria.',
    ticketTypes: [{ id: 'family_group', label: 'Grupo de 3 participantes', price: 270, max: 1, default: 1 }],
  }),
];

const wildlifeActivities = [
  manualActivity({
    id: 'multiacuatic-dolphin-safari',
    title: 'Dolphin Safari — Delfines y Ballenas',
    provider: dolphinProvider,
    sourceUrl: 'https://dolphinwhales.es/product/dolphin-safari',
    price: 40,
    priceUnit: 'persona',
    duration: '3 horas',
    image: images.dolphin,
    category: 'naturaleza',
    location: 'Puerto Rico, Gran Canaria',
    meetingPoint: 'Puerto Base, Puerto Rico',
    pickup: 'Recogida incluida de Mogán a Playa del Cura y de Bahía Feliz a Arguineguín, solicitándola al reservar.',
    groupSize: 'Excursión compartida',
    insurance: 'Según condiciones del operador marítimo',
    cancellationPolicy: dolphinCancellation,
    description: 'Navegación por la costa suroeste de Gran Canaria en busca de delfines y ballenas con guías profesionales.',
    included: ['Excursión marítima con guía', 'Servicio de recogida en las zonas publicadas'],
    notIncluded: ['Servicios no indicados expresamente por el proveedor'],
    ticketTypes: [
      { id: 'adult', label: 'Adultos', price: 40, max: 20, default: 2 },
      { id: 'child', label: 'Menores (3-12)', price: 20, max: 20, default: 0 },
      { id: 'infant', label: 'Bebés (0-2)', price: 0, max: 5, default: 0 },
    ],
    timeSlots: ['10:30'],
    featured: true,
  }),
];

const zeusActivities = [
  manualActivity({
    id: 'zeus-snorkel-mogan',
    title: 'Snorkel Guiado desde Puerto de Mogán',
    provider: zeusProvider,
    sourceUrl: 'https://zeusdivecenter.com/es/reservas-puerto-de-mogan-excursion-de-snorkel-con-barco/',
    price: 69,
    duration: 'Duración a confirmar',
    image: images.dive,
    category: 'buceo',
    location: 'Puerto de Mogán, Gran Canaria',
    meetingPoint: 'Puerto de Mogán',
    groupSize: 'Grupo reducido',
    cancellationPolicy: zeusCancellation,
    description: 'Experiencia de snorkel guiada para principiantes en una bahía protegida, desde barco o costa según el estado del mar.',
    included: ['Guía profesional', 'Máscara full face', 'Selección del mejor punto según el mar'],
    restrictions: ['Edad mínima: 6 años.', 'No apto para personas con problemas de movilidad o en silla de ruedas.'],
  }),
  manualActivity({
    id: 'zeus-certified-diving',
    title: 'Buceo para Buceadores Certificados',
    provider: zeusProvider,
    sourceUrl: 'https://zeusdivecenter.com/es/reservas-buceo-en-gran-canaria-para-buceadores-certificados/',
    price: 116,
    duration: 'Según inmersiones',
    image: images.diveWide,
    category: 'buceo',
    location: 'Sur de Gran Canaria',
    meetingPoint: 'Zeus Dive Center, Playa del Inglés',
    groupSize: 'Grupos reducidos',
    cancellationPolicy: zeusCancellation,
    description: 'Inmersiones para buceadores certificados en distintos puntos del sur, este, oeste y noroeste de Gran Canaria.',
    included: ['Guía profesional de buceo', 'Planificación según nivel y condiciones'],
    notIncluded: ['Alquiler de equipo cuando no esté incluido en la opción reservada'],
    restrictions: ['Es obligatorio disponer de certificación de buceo válida.'],
  }),
  manualActivity({
    id: 'zeus-discover-scuba',
    title: 'Bautizo de Buceo en Playa de Amadores',
    provider: zeusProvider,
    sourceUrl: 'https://zeusdivecenter.com/es/reservas-buceo-al-sur-de-la-isla/',
    price: 85,
    duration: 'Duración a confirmar',
    image: images.dive,
    category: 'buceo',
    location: 'Playa de Amadores, Gran Canaria',
    meetingPoint: 'Playa de Amadores',
    pickup: 'Recogida en hotel según zona y disponibilidad.',
    groupSize: 'Máx. 3 pers. por instructor',
    cancellationPolicy: zeusCancellation,
    description: 'Primera experiencia de buceo en una bahía protegida, con briefing, equipo personal y profundidad máxima de 6 metros.',
    included: ['Instructor de buceo', 'Equipo personal', 'Briefing de seguridad', 'Recogida según zona'],
    restrictions: ['Actividad sujeta a cuestionario médico y condiciones del mar.'],
  }),
  manualActivity({
    id: 'zeus-open-water-course',
    title: 'Curso Open Water Diver SSI / PADI',
    provider: zeusProvider,
    sourceUrl: 'https://zeusdivecenter.com/es/curso-open-water-diver-ssi-padi/',
    price: 450,
    duration: '2 días',
    image: images.diveWide,
    category: 'buceo',
    location: 'Gran Canaria',
    meetingPoint: 'Zeus Dive Center, Playa del Inglés',
    groupSize: 'Curso en grupo reducido',
    cancellationPolicy: zeusCancellation,
    description: 'Curso de certificación internacional con teoría, aguas confinadas e inmersiones en mar abierto.',
    included: ['Formación teórica y práctica', 'Inmersiones en mar abierto', 'Máscara de buceo de regalo'],
    notIncluded: ['Extras y tasas de certificación que el proveedor no detalla en el precio base'],
    restrictions: ['Edad mínima: 10 años.', 'Sujeto a requisitos médicos de buceo.'],
  }),
  manualActivity({
    id: 'zeus-private-sailing-4-5',
    title: 'Velero Privado Vandross VI — 4,5 horas',
    provider: zeusProvider,
    sourceUrl: 'https://zeusdivecenter.com/es/reservas-salida-privada-velero-gran-canaria-4-5-horas/',
    price: 890,
    priceUnit: 'salida privada',
    duration: '4 h 30 min',
    image: images.yacht,
    location: 'Gran Canaria',
    meetingPoint: 'Punto de embarque a confirmar',
    groupSize: 'Grupo privado · capacidad a confirmar',
    cancellationPolicy: zeusCancellation,
    description: 'Navegación privada a bordo del Vandross VI con menú gourmet, vino de la casa y paradas para baño si las condiciones lo permiten.',
    included: ['Velero privado', 'Menú gourmet', 'Vino Vandross', 'Patrón y navegación'],
    ticketTypes: [{ id: 'private_departure', label: 'Salida privada', price: 890, max: 1, default: 1 }],
  }),
  manualActivity({
    id: 'zeus-private-sailing-7',
    title: 'Velero Privado Vandross VI — 7 horas',
    provider: zeusProvider,
    sourceUrl: 'https://zeusdivecenter.com/es/gran-canaria-salida-privada-en-velero-de-7-horas/',
    price: 1090,
    priceUnit: 'salida privada',
    duration: '7 horas',
    image: images.yachtWide,
    location: 'Gran Canaria',
    meetingPoint: 'Punto de embarque a confirmar',
    groupSize: 'Grupo privado · capacidad a confirmar',
    cancellationPolicy: zeusCancellation,
    description: 'Jornada privada de navegación en el Vandross VI con menú gourmet, vino de la casa y tiempo ampliado para disfrutar del mar.',
    included: ['Velero privado', 'Menú gourmet', 'Vino Vandross', 'Patrón y navegación'],
    ticketTypes: [{ id: 'private_departure', label: 'Salida privada', price: 1090, max: 1, default: 1 }],
  }),
];

const nirvanaCancellation = unpublishedCancellation('Nirvana Dreams', 'https://www.nirvanadreams.com/');

const nirvanaActivities = [
  manualActivity({
    id: 'nirvana-day-cruise',
    title: 'Nirvana Day Cruise & Snorkeling',
    provider: nirvanaProvider,
    sourceUrl: 'https://www.nirvanadreams.com/',
    price: 720,
    priceUnit: 'yate privado',
    duration: '4 horas',
    image: images.yacht,
    location: 'Gran Canaria',
    meetingPoint: 'Puerto a confirmar con el proveedor',
    groupSize: 'Hasta 8 pers.',
    cancellationPolicy: nirvanaCancellation,
    description: 'Crucero privado con snorkel, paddle surf, donut tube, bebidas y snacks.',
    included: ['Yate privado con capitán, tripulación y combustible', 'Snorkel y 2 tablas SUP', 'Donut tube', 'Bebidas y snacks'],
    ticketTypes: [{ id: 'private_yacht', label: 'Yate hasta 8 personas', price: 720, max: 1, default: 1 }],
  }),
  manualActivity({
    id: 'nirvana-gui-gui',
    title: 'Nirvana Güi Güi Hidden Gem Tour',
    provider: nirvanaProvider,
    sourceUrl: 'https://www.nirvanadreams.com/',
    price: 1195,
    priceUnit: 'yate privado',
    duration: '6 horas',
    image: images.yachtWide,
    location: 'Costa oeste de Gran Canaria',
    meetingPoint: 'Puerto a confirmar con el proveedor',
    groupSize: 'Hasta 8 pers.',
    cancellationPolicy: nirvanaCancellation,
    description: 'Excursión privada a la playa de Güi Güi con actividades acuáticas, bebidas premium, snacks y paella.',
    included: ['Yate privado con tripulación y combustible', 'Snorkel, SUP, donut tube y sea scooter', 'Bebidas premium, snacks y paella'],
    ticketTypes: [{ id: 'private_yacht', label: 'Yate hasta 8 personas', price: 1195, max: 1, default: 1 }],
    featured: true,
  }),
  manualActivity({
    id: 'nirvana-sunset',
    title: 'Nirvana Sunset Tour',
    provider: nirvanaProvider,
    sourceUrl: 'https://www.nirvanadreams.com/',
    price: 540,
    priceUnit: 'yate privado',
    duration: '3 horas',
    image: images.sunset,
    location: 'Gran Canaria',
    meetingPoint: 'Puerto a confirmar con el proveedor',
    groupSize: 'Hasta 8 pers.',
    cancellationPolicy: nirvanaCancellation,
    description: 'Puesta de sol privada en yate con bebidas, snacks, snorkel, paddle surf y parada de baño opcional.',
    included: ['Yate privado con tripulación y combustible', 'Snorkel, SUP y donut tube', 'Bebidas y snacks'],
    ticketTypes: [{ id: 'private_yacht', label: 'Yate hasta 8 personas', price: 540, max: 1, default: 1 }],
  }),
  manualActivity({
    id: 'nirvana-private-yacht',
    title: 'Nirvana Private Yacht Tour',
    provider: nirvanaProvider,
    sourceUrl: 'https://www.nirvanadreams.com/',
    price: 540,
    priceUnit: 'yate privado',
    duration: '3 horas',
    image: images.yacht,
    location: 'Gran Canaria',
    meetingPoint: 'Puerto a confirmar con el proveedor',
    groupSize: 'Hasta 8 pers.',
    cancellationPolicy: nirvanaCancellation,
    description: 'Tour privado de relax y navegación con equipo de snorkel, paddle surf, donut tube, bebidas y snacks.',
    included: ['Yate privado con tripulación y combustible', 'Snorkel, SUP y donut tube', 'Bebidas y snacks'],
    ticketTypes: [{ id: 'private_yacht', label: 'Yate hasta 8 personas', price: 540, max: 1, default: 1 }],
  }),
  manualActivity({
    id: 'nirvana-all-inclusive-water-adventure',
    title: 'Nirvana All Inclusive Water Adventure',
    provider: nirvanaProvider,
    sourceUrl: 'https://www.nirvanadreams.com/',
    price: 780,
    priceUnit: 'yate privado',
    duration: '3 horas',
    image: images.jetSki,
    location: 'Gran Canaria',
    meetingPoint: 'Puerto a confirmar con el proveedor',
    groupSize: 'Hasta 6 pers. en tarifa base',
    cancellationPolicy: nirvanaCancellation,
    description: 'Salida privada con una aventura acuática a elegir entre jet ski, banana o Crazy UFO, además de snorkel y paddle surf.',
    included: ['Yate privado con tripulación y combustible', 'Una actividad acuática incluida', 'Snorkel, SUP, donut tube y sea scooter', 'Bebidas y snacks'],
    ticketTypes: [
      { id: 'base_group', label: 'Grupo hasta 6 personas', price: 780, max: 1, default: 1 },
      { id: 'extra_couple', label: 'Pareja extra (máx. 2 pers.)', price: 150, max: 1, default: 0 },
    ],
  }),
  manualActivity({
    id: 'nirvana-dolphin-chill',
    title: 'Nirvana Dolphin Spotting & Chill Cruise',
    provider: nirvanaProvider,
    sourceUrl: 'https://www.nirvanadreams.com/',
    price: 900,
    priceUnit: 'yate privado',
    duration: '5 horas',
    image: images.dolphin,
    location: 'Gran Canaria',
    meetingPoint: 'Puerto a confirmar con el proveedor',
    groupSize: 'Hasta 8 pers.',
    cancellationPolicy: nirvanaCancellation,
    description: 'Crucero privado orientado a la observación ocasional de delfines, aves y vida marina. Los avistamientos no están garantizados.',
    included: ['Yate privado con tripulación y combustible', 'Navegación de observación de fauna'],
    notIncluded: ['Avistamiento garantizado de delfines'],
    ticketTypes: [{ id: 'private_yacht', label: 'Yate hasta 8 personas', price: 900, max: 1, default: 1 }],
  }),
];

const molinaCancellation = unpublishedCancellation(
  'Watersports Luis Molina',
  'https://www.watersportsluismolina.com/precios/'
);

function molinaActivity(options) {
  return manualActivity({
    provider: molinaProvider,
    sourceUrl: 'https://www.watersportsluismolina.com/precios/',
    location: 'Anfi del Mar, Gran Canaria',
    meetingPoint: 'Anfi del Mar Water Sports',
    pickup: 'Consultar recogida y punto exacto con OWA.',
    cancellationPolicy: molinaCancellation,
    ...options,
  });
}

const molinaActivities = [
  molinaActivity({
    id: 'molina-jet-ski-rental',
    title: 'Moto Acuática en Anfi del Mar',
    price: 60,
    priceUnit: 'opción',
    duration: '20 o 30 minutos',
    image: images.jetSki,
    description: 'Conducción de moto acuática con opciones individuales y dobles de 20 o 30 minutos.',
    ticketTypes: [
      { id: 'single_20', label: '20 min · 1 persona', price: 60 },
      { id: 'double_20', label: '20 min · 2 personas', price: 70 },
      { id: 'single_30', label: '30 min · 1 persona', price: 90 },
      { id: 'double_30', label: '30 min · 2 personas', price: 90 },
    ],
  }),
  molinaActivity({
    id: 'molina-jet-ski-safari',
    title: 'Jet Ski Safari',
    price: 135,
    priceUnit: 'moto',
    duration: '1 o 2 horas',
    image: images.jetSki,
    description: 'Safari guiado en moto acuática por la costa con opciones individual, doble y recorrido de dos horas.',
    ticketTypes: [
      { id: 'single_60', label: '1 hora', price: 135 },
      { id: 'double_60', label: 'Moto doble · 1 hora', price: 145 },
      { id: 'one_or_two_120', label: '1 o 2 personas · 2 horas', price: 235 },
    ],
    featured: true,
  }),
  molinaActivity({
    id: 'molina-flyboard',
    title: 'Flyboard',
    price: 80,
    duration: '20 o 30 minutos',
    image: images.parasailing,
    description: 'Sesión de flyboard en Anfi del Mar con dos duraciones disponibles.',
    ticketTypes: [
      { id: 'flyboard_20', label: '20 minutos', price: 80 },
      { id: 'flyboard_30', label: '30 minutos', price: 100 },
    ],
  }),
  molinaActivity({
    id: 'molina-parasailing',
    title: 'Paracaídas Acuático — Parasailing',
    price: 50,
    priceUnit: 'vuelo',
    duration: '10 minutos',
    image: images.parasailing,
    description: 'Vuelo en parasailing para una, dos o tres personas, con un peso máximo conjunto de 200 kg.',
    ticketTypes: [
      { id: 'solo', label: '1 persona', price: 50 },
      { id: 'double', label: '2 personas', price: 90 },
      { id: 'triple', label: '3 personas · máx. 200 kg', price: 130 },
      { id: 'spectator', label: 'Espectador a bordo', price: 15 },
    ],
    restrictions: ['Peso máximo conjunto para tres personas: 200 kg.', 'Actividad sujeta a viento y estado del mar.'],
  }),
  molinaActivity({
    id: 'molina-speed-boat',
    title: 'Speed Boat',
    price: 40,
    duration: '20 min o 1 h 15 min',
    image: images.boatParty,
    description: 'Paseo rápido en embarcación con opción corta de 20 minutos o recorrido ampliado.',
    ticketTypes: [
      { id: 'speed_20', label: '20 minutos · 1 persona', price: 40 },
      { id: 'speed_75', label: '1 h 15 min · 1 persona', price: 59 },
    ],
  }),
  molinaActivity({
    id: 'molina-banana',
    title: 'Banana Boat',
    price: 15,
    duration: '10 minutos',
    image: images.jetSki,
    description: 'Recorrido de banana boat arrastrado por lancha para grupos.',
    groupSize: 'Mín. 3 pers.',
    ticketTypes: [{ id: 'person', label: 'Personas · mínimo 3', price: 15, max: 12, default: 3 }],
    restrictions: ['Reserva mínima de 3 participantes.'],
  }),
  molinaActivity({
    id: 'molina-crazy-sofa',
    title: 'Crazy Sofa',
    price: 25,
    duration: '10 minutos',
    image: images.jetSki,
    description: 'Actividad de velocidad sobre sofá hinchable arrastrado por lancha.',
  }),
  molinaActivity({
    id: 'molina-paddle-surf',
    title: 'Alquiler de Paddle Surf',
    price: 15,
    duration: '1 o 2 horas',
    image: images.paddle,
    description: 'Alquiler de tabla de paddle surf en Anfi del Mar.',
    ticketTypes: [
      { id: 'sup_60', label: '1 hora', price: 15 },
      { id: 'sup_120', label: '2 horas', price: 20 },
    ],
  }),
  molinaActivity({
    id: 'molina-waterbull',
    title: 'Water Bull',
    price: 25,
    duration: '10-12 minutos',
    image: images.jetSki,
    description: 'Actividad acuática de arrastre sobre hinchable Water Bull.',
  }),
  molinaActivity({
    id: 'molina-wakeboard',
    title: 'Wakeboard',
    price: 60,
    duration: '15 o 30 minutos',
    image: images.paddle,
    description: 'Sesión de wakeboard con opción de 30 minutos acompañada por profesor.',
    ticketTypes: [
      { id: 'wake_15', label: '15 minutos', price: 60 },
      { id: 'wake_30_teacher', label: '30 minutos con profesor', price: 80 },
    ],
  }),
  molinaActivity({
    id: 'molina-pedal-boat',
    title: 'Coche Patín',
    price: 20,
    priceUnit: 'embarcación',
    duration: '1 hora',
    image: images.paddle,
    description: 'Alquiler de coche patín para navegar frente a Anfi del Mar.',
    groupSize: 'Hasta 4 pers.',
    ticketTypes: [{ id: 'pedal_boat', label: 'Coche patín hasta 4 personas', price: 20 }],
  }),
  molinaActivity({
    id: 'molina-kayak',
    title: 'Alquiler de Kayak',
    price: 10,
    priceUnit: 'canoa',
    duration: '1 hora',
    image: images.paddle,
    description: 'Alquiler de kayak individual o doble en Anfi del Mar.',
    ticketTypes: [
      { id: 'single_kayak', label: 'Canoa individual', price: 10 },
      { id: 'double_kayak', label: 'Canoa doble', price: 15 },
    ],
  }),
  molinaActivity({
    id: 'molina-water-ski',
    title: 'Esquí Acuático',
    price: 60,
    duration: '15 o 30 minutos',
    image: images.paddle,
    description: 'Sesión de esquí acuático con opción de 30 minutos acompañada por profesor.',
    ticketTypes: [
      { id: 'ski_15', label: '15 minutos', price: 60 },
      { id: 'ski_30_teacher', label: '30 minutos con profesor', price: 80 },
    ],
  }),
  molinaActivity({
    id: 'molina-sun-pack',
    title: 'Sun Pack',
    price: 89,
    priceUnit: 'persona desde',
    duration: 'Pack de actividades',
    image: images.parasailing,
    description: 'Pack con moto acuática, parasailing, banana o Crazy Sofa y servicio de hamaca y sombrilla.',
    included: ['Moto acuática', 'Parasailing', 'Banana o Crazy Sofa', 'Hamaca y sombrilla'],
    ticketTypes: [
      { id: 'pack_two', label: 'Pack para 2 personas', price: 178, max: 1, default: 1 },
      { id: 'pack_one', label: 'Pack para 1 persona', price: 109, max: 1, default: 0 },
    ],
  }),
  molinaActivity({
    id: 'molina-fun-pack',
    title: 'Fun Pack',
    price: 73,
    priceUnit: 'persona desde',
    duration: 'Pack de actividades',
    image: images.jetSki,
    description: 'Pack combinado de moto acuática y parasailing.',
    included: ['Moto acuática', 'Parasailing'],
    ticketTypes: [
      { id: 'pack_two', label: 'Pack para 2 personas', price: 146, max: 1, default: 1 },
      { id: 'pack_one', label: 'Pack para 1 persona', price: 99, max: 1, default: 0 },
    ],
  }),
  molinaActivity({
    id: 'molina-adventure-pack',
    title: 'Adventure Pack',
    price: 99,
    priceUnit: 'persona desde',
    duration: 'Pack de actividades',
    image: images.boatParty,
    description: 'Pack combinado de Speed Boat, parasailing y Crazy Sofa.',
    included: ['Speed Boat · 20 minutos', 'Parasailing · 8-10 minutos', 'Crazy Sofa · 10-12 minutos'],
    ticketTypes: [
      { id: 'pack_two', label: 'Pack para 2 personas', price: 198, max: 1, default: 1 },
      { id: 'pack_one', label: 'Pack para 1 persona', price: 105, max: 1, default: 0 },
    ],
  }),
  molinaActivity({
    id: 'molina-stingray-catamaran',
    title: 'Catamarán Stingray',
    sourceUrl: 'https://www.watersportsluismolina.com/actividades/catamaran-stingray/',
    priceSourceUrl: 'https://www.watersportsluismolina.com/',
    price: 79,
    duration: '4 horas',
    image: images.catamaran,
    location: 'Puerto de Mogán, Gran Canaria',
    meetingPoint: 'Puerto de Mogán',
    pickup: 'Recogida incluida desde hoteles del sur, según las zonas publicadas.',
    groupSize: 'Grupo reducido',
    description: 'Navegación en catamarán por la costa de Gran Canaria con almuerzo, bebidas, snorkel y paddle surf.',
    included: ['Almuerzo con productos locales', 'Bebidas ilimitadas', 'Snorkel y paddle surf', 'Recogida desde hoteles del sur'],
    featured: true,
  }),
  molinaActivity({
    id: 'molina-bluefin-shared',
    title: 'Catamarán Bluefin — Salida Compartida',
    sourceUrl: 'https://www.watersportsluismolina.com/actividades/catamaran-bluefin/',
    price: 99,
    duration: 'Duración a confirmar',
    image: images.catamaran,
    location: 'Puerto de Mogán, Gran Canaria',
    meetingPoint: 'Puerto de Mogán',
    groupSize: 'Hasta 12 pers.',
    description: 'Salida compartida en el catamarán Lagoon 42 Bluefin con patrón profesional.',
    included: ['Patrón profesional', 'Navegación en grupo reducido'],
  }),
  molinaActivity({
    id: 'molina-bluefin-private',
    title: 'Catamarán Bluefin — Salida Privada',
    sourceUrl: 'https://www.watersportsluismolina.com/actividades/catamaran-bluefin/',
    price: 900,
    priceUnit: 'salida privada desde',
    duration: '2, 3, 4, 6 u 8 horas',
    image: images.catamaran,
    location: 'Puerto de Mogán, Gran Canaria',
    meetingPoint: 'Puerto de Mogán',
    groupSize: 'Hasta 12 pers.',
    description: 'Alquiler privado del catamarán Lagoon 42 Bluefin con patrón profesional y duración personalizable.',
    included: ['Catamarán privado', 'Patrón profesional'],
    ticketTypes: [{ id: 'private_departure', label: 'Salida privada desde', price: 900, max: 1, default: 1 }],
  }),
];

const otherActivities = [
  manualActivity({
    id: 'obycat-gran-canaria',
    title: 'Obycat Gran Canaria — Catamarán Todo Incluido',
    provider: { id: 'obycat', name: 'Obycat' },
    sourceUrl: 'https://www.obycat.com/',
    priceSourceUrl: 'https://www.facebook.com/obycat/',
    price: 69,
    duration: '4 horas',
    image: images.catamaran,
    location: 'Puerto Rico, Gran Canaria',
    meetingPoint: 'Puerto Rico, punto exacto a confirmar',
    groupSize: 'Excursión compartida',
    cancellationPolicy: unpublishedCancellation('Obycat', 'https://www.obycat.com/'),
    description: 'Excursión en catamarán por Gran Canaria con comida, bebidas y material de snorkel.',
    included: ['Comida y bebidas', 'Material de snorkel', 'Tripulación profesional'],
    ticketTypes: [
      { id: 'adult', label: 'Adultos', price: 69, max: 30, default: 2 },
      { id: 'child', label: 'Niños', price: 45, max: 20, default: 0 },
    ],
  }),
  manualActivity({
    id: 'puerto-rico-boat-party',
    title: 'Boat Party desde Puerto Rico',
    provider: { id: 'getyourguide-partner', name: 'Operador publicado en GetYourGuide' },
    sourceUrl: 'https://www.getyourguide.com/gran-canaria-l418/desde-puerto-rico-fiesta-en-barco-por-la-costa-t754827/',
    price: 60,
    duration: '4 horas',
    image: images.boatParty,
    location: 'Puerto Rico, Gran Canaria',
    meetingPoint: 'Puerto Base, Puerto Rico',
    pickup: 'Punto de encuentro en el puerto; confirmar instrucciones en la reserva.',
    groupSize: 'Fiesta compartida · solo adultos',
    cancellationPolicy: getYourGuideCancellation,
    description: 'Fiesta en barco por la costa suroeste de Gran Canaria con DJ, música, bebidas y ambiente para adultos.',
    included: ['Navegación de 4 horas', 'DJ y música', 'Bebidas según la opción del operador'],
    notIncluded: ['Extras premium no indicados en la tarifa base'],
    restrictions: ['Actividad para mayores de 18 años.', 'Es necesario presentar identificación válida.'],
    timeSlots: ['15:30'],
    featured: true,
  }),
];

export const additionalActivities = [
  ...infinityActivities,
  ...buggyActivities,
  ...wildlifeActivities,
  ...zeusActivities,
  ...nirvanaActivities,
  ...molinaActivities,
  ...otherActivities,
];
